apiVersion: v1
kind: Secret
metadata:
  name: traintrack-backend-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:traintrack-dev-password@traintrack-postgres:5432/traintrack?schema=public
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traintrack-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traintrack-backend
  template:
    metadata:
      labels:
        app: traintrack-backend
    spec:
      containers:
        - name: traintrack-backend
          image: ghcr.io/elarkaso/train-track-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: FRONTEND_URL
              value: http://traintrack.k8slab
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: traintrack-backend-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: traintrack-backend
spec:
  selector:
    app: traintrack-backend
  ports:
    - port: 3000
      targetPort: 3000